apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: cocktails
spec:
  replicas: 1
  selector:
    matchLabels: { app: api }
  template:
    metadata:
      labels: { app: api }
    spec:
      containers:
        - name: api
          image: ivanoskif/ci-cd-cocktails-backend:latest
          imagePullPolicy: Always
          ports: [{ containerPort: 8000 }]
          env:
            - name: MONGO_USER
              valueFrom: { secretKeyRef: { name: mongo-secret, key: MONGO_INITDB_ROOT_USERNAME } }
            - name: MONGO_PASS
              valueFrom: { secretKeyRef: { name: mongo-secret, key: MONGO_INITDB_ROOT_PASSWORD } }
            - name: MONGO_URI
              value: mongodb://$(MONGO_USER):$(MONGO_PASS)@mongo:27017/?authSource=admin

            - name: MONGO_DB
              valueFrom: { configMapKeyRef: { name: app-config, key: MONGO_DB } }
            - name: CORS_ORIGINS
              valueFrom: { configMapKeyRef: { name: app-config, key: CORS_ORIGINS } }
          readinessProbe:
            httpGet: { path: /api/health, port: 8000 }
            initialDelaySeconds: 5
            periodSeconds: 5
